name: Generate README.md

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

env:
  GITHUB_NAME: susucain
  GITHUB_EMAIL: susucain@gmail.com

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
          
      - name: Generate readme.md
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn generate
        
      - name: Push README
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Refresh README'
          author_name: ${{ env.GITHUB_NAME }}
          author_email: ${{ env.GITHUB_EMAIL }}
